# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
R:
  - devel
dist: trusty
os:
  - linux
  - osx

env:
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_LATEX_VIGNETTES=FALSE
    - _R_CHECK_WEAVE_VIGNETTES=FALSE

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
