# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
R:
  - release
dist: trusty
os:
  - linux

env:
  global:
    - NOT_CRAN = TRUE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_LATEX_VIGNETTES=FALSE
    - _R_CHECK_WEAVE_VIGNETTES=FALSE
    - VDIFFR_RUN_TESTS = TRUE

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

script:
  - R -e 'install.packages("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(tarball = ".")'
  skip_cleanup: true
